from fastapi import APIRouter, UploadFile, File, HTTPException
from schemas.response import TryOnResponse
from utils.validators import validate_image
from services.image_service import save_temp_upload, save_temp_bytes, cleanup_temp_files
from services.gemini_service import generate_tryon_image
from services.appwrite_service import upload_generated_image
import logging

router = APIRouter()
logger = logging.getLogger(__name__)

@router.get("/", response_model=dict)
async def health_check():
    """
    Health check endpoint to verify that the service is running.
    """
    return {"status": "ok", "message": "Service is running."}

@router.post("/tryon", response_model=TryOnResponse)
async def process_virtual_tryon(
    person_image: UploadFile = File(..., description="Full body image of the person."),
    cloth_image: UploadFile = File(..., description="Image of the clothing item.")
):
    temp_person_path = None
    temp_cloth_path = None
    temp_generated_path = None

    try:
        # 1. Validate both files
        await validate_image(person_image)
        await validate_image(cloth_image)

        # 2. Save uploads temporarily
        temp_person_path = await save_temp_upload(person_image)
        temp_cloth_path = await save_temp_upload(cloth_image)

        # 3. Send to Gemini and get generated bytes
        generated_bytes = await generate_tryon_image(temp_person_path, temp_cloth_path)
        
        # 4. Save generated image temporarily
        temp_generated_path = await save_temp_bytes(generated_bytes, ext=".png")

        # 5. Upload to Appwrite
        upload_result = await upload_generated_image(temp_generated_path)

        # 6. Return response
        return TryOnResponse(
            success=True,
            image_url=upload_result["url"],
            file_id=upload_result["file_id"],
            message="Virtual try-on generated successfully."
        )

    except Exception as e:
        logger.error(f"Error in try-on workflow: {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))
        
    finally:
        # 7. Cleanup temp files regardless of success or failure
        cleanup_temp_files(temp_person_path, temp_cloth_path, temp_generated_path)